# Generated by Django 5.2.6 on 2025-09-16 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.AutoField(db_column='cliente_id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('telefono', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
    ]
